# Application Name
spring.application.name=SimActivationPortal

# Server Port
server.port=8080

# MySQL Database Configuration
spring.datasource.url=jdbc:mysql://avnadmin:AVNS_S7DBxjPgez1QDrwtkau@mysql-2f74e44a-allwin-2436.a.aivencloud.com:18101/defaultdb?ssl-mode=REQUIRED
spring.datasource.username=avnadmin
spring.datasource.password=AVNS_S7DBxjPgez1QDrwtkau
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Jackson Date Format
spring.jackson.date-format=yyyy-MM-dd
spring.jackson.serialization.write-dates-as-timestamps=false
